name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Run tests
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        package-manager: yarn
        test-script: yarn test --all --collectCoverage